spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    jdbcUrl: jdbc:mysql://localhost:3306/cniao5
    username: admin
    password: admin

config:
  jwt:
    secret: abcdefg1234567
    expire: 36000000
